name: MT5 Headless

on:
  workflow_dispatch:

jobs:
  mt5:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download MT5
        shell: cmd
        run: |
          curl -L "https://download.mql5.com/cdn/web/metaquotes.software.corp/mt5/mt5setup.exe" -o mt5setup.exe

      - name: Install MT5 silently
        shell: cmd
        run: |
          mt5setup.exe /auto

      - name: Find MT5 terminal
        shell: cmd
        run: |
          where /r "C:\Program Files" terminal64.exe
          where /r "C:\Program Files (x86)" terminal64.exe

      - name: Run MT5 from CMD
        shell: cmd
        run: |
          cd /d "C:\Program Files\MetaTrader 5"
          terminal64.exe /config:"%GITHUB_WORKSPACE%\mt5.ini"
